Repository enigma-dev/enigma-dev, pull requests merged in 2018-10, with the labels that each got.

#1396 Generic Matrices Using OpenGL Mathematics (GLM)
  .travis.yml
  ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11d3d.cpp
  ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11matrix.cpp
  ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11vertex.cpp
  ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9d3d.cpp
  ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9matrix.cpp
  ENIGMAsystem/SHELL/Graphics_Systems/General/GSd3d.h
  ENIGMAsystem/SHELL/Graphics_Systems/General/GSmath.h
  ENIGMAsystem/SHELL/Graphics_Systems/General/GSmatrix.cpp
  ENIGMAsystem/SHELL/Graphics_Systems/General/GSmatrix.h
  ENIGMAsystem/SHELL/Graphics_Systems/General/GSmatrix_impl.h
  ENIGMAsystem/SHELL/Graphics_Systems/None/NONEmatrix.cpp
  ENIGMAsystem/SHELL/Graphics_Systems/None/fillin.cpp
  ENIGMAsystem/SHELL/Graphics_Systems/None/fillin.h
  ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLd3d.cpp
  ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLmatrix.cpp
  ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3d3d.cpp
  ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3matrix.cpp
  ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3matrix.h
  ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3shader.h
  ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3vertex.cpp
  appveyor.yml
Labels: Dependencies, Feedback Needed, Graphics

#1399 Cleanup Motion Planning & Paths Graphics
  ENIGMAsystem/SHELL/Universal_System/Extensions/MotionPlanning/motion_planning.cpp
  ENIGMAsystem/SHELL/Universal_System/Extensions/Paths/path_functions.cpp
Labels: Extensions, Graphics

#1401 GRPC Resources Fix
  CommandLine/emake/Server.cpp
Labels: Asset Pipeline, Bug, Compiler, Reproducible

#1402 GRPC Methods for System Info
  CommandLine/emake/Main.cpp
  CommandLine/emake/OptionsParser.cpp
  CommandLine/emake/OptionsParser.hpp
  CommandLine/emake/Server.cpp
  CommandLine/emake/Server.hpp
  CommandLine/protos/server.proto
Labels: Asset Pipeline, Compiler, Cross-compile

#1404 Fix Platform Inspection False Positives
  CompilerSource/filesystem/file_find.cpp
  CompilerSource/filesystem/file_find.h
  CompilerSource/settings-parse/crawler.cpp
  ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSfilemanip.cpp
Labels: Asset Pipeline, Bug, Compiler, Confirmed, Error, Reproducible

#1407 Cleanup a few includes causing JDI errors
  ENIGMAsystem/SHELL/Collision_Systems/BBox/include.h
  ENIGMAsystem/SHELL/Collision_Systems/Precise/include.h
  ENIGMAsystem/SHELL/Graphics_Systems/General/GSsprite.cpp
  ENIGMAsystem/SHELL/Graphics_Systems/General/GSsprite.h
  ENIGMAsystem/SHELL/Universal_System/Extensions/MotionPlanning/mp_movement.h
Labels: Compile Error, Extensions, Graphics, Universal System

#1416 Fix GRPC Access of Non-function Resources
  CommandLine/emake/Server.cpp
Labels: Asset Pipeline, Bug, Compiler, Confirmed, Parsing, Reproducible

#1408 Fixed "All Files (*.*;*)" File Filter on Mac
  ENIGMAsystem/SHELL/Widget_Systems/General/tinyfiledialogs/dialogs.cpp
Labels: Widgets

#1418 Settings Proto Conversion to EnigmaStruct
  CommandLine/emake/Proto2ES.cpp
Labels: Asset Pipeline

#1419 Read GMK Settings in libEGM
  CommandLine/libEGM/gmk.cpp
  CommandLine/protos/Settings.proto
Labels: Asset Pipeline

#1420 libEGM GMK Transparency Fix
  CommandLine/emake/Proto2ES.cpp
  CommandLine/libEGM/gmk.cpp
  CommandLine/protos/Background.proto
  CommandLine/protos/Sprite.proto
Labels: Asset Pipeline

#1417 Aliases for System Info
  CommandLine/emake/OptionsParser.cpp
  CommandLine/emake/Server.cpp
  CommandLine/protos/server.proto
Labels: Asset Pipeline, Compiler

#1421 Async Compile & Remote Logging
  CommandLine/emake/EnigmaCallbacks.cpp
  CommandLine/emake/EnigmaCallbacks.hpp
  CommandLine/emake/EnigmaPlugin.cpp
  CommandLine/emake/EnigmaPlugin.hpp
  CommandLine/emake/Main.cpp
  CommandLine/emake/Server.cpp
  CommandLine/emake/Server.hpp
  CommandLine/protos/Makefile
  CommandLine/protos/server.proto
Labels: Asset Pipeline
